### PR TITLE
Consume bosh link for postgres connection

### PR DESCRIPTION
**Pull request by vChrisR**

### CODE REVIEW

**Comment by ashwin-venkatesh** [comment]
Which release do you have in mind as providing the database link? We looked at the database link provided by the postgres release, and it seems like many other properties are provided by the link like the port, dbname, password, user etc. Ideally we would like a solution that consumes as much from the link as possible. Also, currently, as there does not seem to be a standardization that both the postgres and mysql release use with their provided links, we probably want to defer this feature for now.

**Comment by crawsible** [comment]
@vChrisR any response for @ashwin-venkatesh? We'd like to know which release's link you're interested in consuming. With more information we can talk to the teams that maintain DB links and ask them to standardize.

**Comment by vChrisR** [comment]
Sorry for the late reply. I tested this with the cloudfoundry/postgres-release. I want this mainly to easily deploy credhub alongside with concourse in the same deployment and using the same postgres server without having to configure static IP adresses.

By PR uses the database type link that is exposted by cloudfoundry/postgres-release. I only use the db server addres from the link. That is the minimum I needed to deploy credhub without having to specifiy fixed IPs.

**Comment by zmb3** [comment]
I too am interested in this exact use case (consuming a link from the postgres release in order to deploy CredHub alongside Concourse without needing to use a static IP for the DB instance).

> Ideally we would like a solution that consumes as much from the link as possible

I agree that would be great in the _ideal_ case.  In the common case though, simply consuming the IP would be a nice MVP that would simplify this particular use case.

FWIW, this use case is quite common in the field.  With the advent of [pcf-pipelines](https://github.com/pivotal-cf/pcf-pipelines), more and more customers are using Concourse to deploy PCF.  This requires IaaS credentials, which almost necessitates deployment of a credential manager alongside Concourse.  Since Concourse requires postgres there's already a DB in the deployment that we can use.

**Comment by kstrini** [comment]
👍

**Comment by crawsible** [comment]
@vChrisR Thanks for your patience. We're making extensive changes to the way we consume our manifest configuration which this PR would be disruptive of, but we plan on adding the ability to consume a db link for its address afterwards. We will ping back when we've incorporated this change.

**Comment by clhynfield** [comment]
Working with a customer right now whose Concourse+CredHub deployment would be simplified if credhub-release supported a db link. :+1:

**Comment by athornton2012** [comment]
@vChrisR we have pulled in your changes and made a few adjustments. On master now, if you want to take a look! Thanks for the PR!

**Pull request merged**
